### ISSUE TITLE
Redirect old links from exceptions to new targets on page

### ISSUE THREAD

**Issue by danielcompton** [SeleniumHQ/seleniumhq.github.io#170]
## 🚀 Feature Proposal for the site or the documentation

Exceptions from Selenium 3.141.59 show up like:

```
org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method" : "css selector" "selector": " *[name='card']"}
(Session info: chrome=78.0.3904.108)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html        
```

If you open that link to https://www.seleniumhq.org/exceptions/no_such_element.html it redirects to the exceptions page https://selenium.dev/exceptions/. It would be nice if it redirected to https://selenium.dev/exceptions/#no_such_element so that the exact exception that was thrown is shown.

## Motivation

This would make it easier for people to read the docs about their exception.

## Example

Provided above I think?

**Comment by Harsha509** [comment]
Hi @danielcompton ,

Thanks for the inputs. THis is fixed in selenium with commit https://github.com/SeleniumHQ/selenium/commit/07ee491572f88790e598042ae779c44d3c1b3015

Will be available in next release maybe.

Thanks,
Sri Harsha

**Comment by Harsha509** [comment]
Hi @diemol . This can be closed now i think.

**Comment by diemol** [comment]
Yep @Harsha509, thank you.

**Comment by danielcompton** [comment]
Hi folks, this issue is about setting up website redirects. I don’t think it is fixed?

**Comment by diemol** [comment]
Well, ideally it could be redirected, but we did not have enough bandwidth when the new site was released and the complexity the old one had, so we opted for the easiest and quickest solution, which was to redirect to the whole page. Considering that there are only 3 exceptions mentioned there, we felt that it was enough since it is not an endless amount of text the user has to navigate through.
Also, for the Selenium 4 alphas, the URLs are now correct.
Having said that, we believe that spending effort on having a more precise redirect won't have much more added value.
